# Checks code with Rector and auto-commits
name: RectorCI

on:
#  pull_request: null
  pull_request:
    branches: ["testing"]

jobs:
  rector:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      -
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/checkout@v3
        with:
          # Must be used to trigger workflow after push
          token: ${{ secrets.ACCESS_TOKEN }}

      -
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --ansi

      - name: Run Rector
        run: bin/rector --ansi

      -
        # commit only to core contributors who have repository access
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[rector] Rector fixes'
          commit_author: 'GitHub Action <actions@github.com>'
          commit_user_email: 'action@github.com'